GET http://localhost:3000/students/ HTTP/1.1

PATCH http://localhost:3000/students/5 HTTP/1.1
content-type: application/json

{
    "firstName": "XXXX"
}

PATCH http://localhost:3000/students/2 HTTP/1.1
content-type: application/json

{
    "firstName": "OOOOO"
}

GET http://localhost:3000/students/2 HTTP/1.1

DELETE http://localhost:3000/students/8 HTTP/1.1

GET http://localhost:3000/students/ HTTP/1.1

DELETE http://localhost:3000/students/1 HTTP/1.1

GET http://localhost:3000/students/ HTTP/1.1

GET http://localhost:3000/students/1 HTTP/1.1

GET http://localhost:3000/students/2 HTTP/1.1
